### ISSUE TITLE
Paginators should support sort order independently from their collections (plugin, gist)

### ISSUE THREAD

**Issue by indolent-gnathostome** [ruhoh/ruhoh.rb#255]
I have a collection that needs to:
- Paginate in **_ascending_** order _(page 1 = oldest)_.
- Sort posts on each page in **_descending_** order _(top post = newest)_.  

This is a friendlier way to display some content, and makes each paginated url more bookmark-friendly.

The **config.yml** could support this with an optional 'sort' parameter within a collection's paginator:

``` yaml
# ...in config.yml:
posts:
  sort: ["date", "desc"]
  paginator:
    enable: true
    sort: 'asc' # <-- NEW OPTION (default: 'desc' )
# ...and so on
```

I've implemented this behavior as a plugin (+cucumber test), available in this gist: 
- https://gist.github.com/7974134

Ideally, this would be a feature of the core paginator.
