### ISSUE TITLE
Custom Meta-Data Templating

### ISSUE THREAD

**Issue by jacobmgreer** [ruhoh/ruhoh.rb#90]
I've been creating a new theme for my blog but am having trouble with templating.
In the following example, the array of (link, title) of (toc, two) are currently rendering like:

``` html
<li><a href="#b"></a></li>
<li><a href="#">Open Data Movements</a></li>
<li><a href="#c"></a></li>
<li><a href="#">Open Access to the Network</a></li>
```

Rather than

``` html
<li><a href="#b">Open Data Movements</a></li>
<li><a href="#c">Open Access to the Network</a></li>
```

All the related code:

custom meta-data in a post (I'm trying to create a table of contents, it's generally working)

``` yaml
toc:
 - one: Background Thoughts
 - two: [link: a, title: Personal History with Twitter]
 - two: [link: b, title: Open Data Movements]
 - two: [link: c, title: Open Access to the Network]
 - two: [link: d, title: Lowering Barriers]
 - two: [link: e, title: "Technocraticly Inclined Future?"]
 - one: Social Conferences and Events
 - two: [link: f, title: Live Tweeting to Lower Barriers]
 - two: [link: g, title: Opening Access Through Sharing]
 - two: [link: h, title: Common Mistakes by Social Events]
 - two: [link: i, title: "Twitter HQ: Rethink Event Accounts"]
 - two: [link: j, title: Live Tweet Timeline Flooding]
 - two: [link: k, title: Circles in Crowd Learning Networks]
 - one: Review of Main Points
```

Table of contents partial:

``` html
{{# one }}
    <li class="nav-header">{{ . }}</li>
{{/ one }}
{{# two }}
    <li><a href="#{{ link }}">{{ title }}</a></li>
{{/ two }}
```

Template code: 

``` html
<ul class="nav nav-list" id="toc">
    {{# page.toc }}
        {{> toc }}
    {{/ page.toc }}
</ul>
```
